### ISSUE TITLE
Segregate handlers configuration

### ISSUE THREAD

**Issue by TomerFi** [TomerFi/auto-me-bot#46]
### What did you have in mind?

Currently, all handlers have access to the full configuration file,
this is unwanted - the handlers don't need each other's configuration,
keeping it this way might invite coupling as this repo evolve and isn't the most secure thing to do.

### Are you trying to fix a problem?

Prevent handlers from accessing each other's configuration.

### Any lead on how this feature can be implemented?

As of the time of writing this, we have 3 handlers:
- [pr-conventional-commits](https://github.com/TomerFi/auto-me-bot/blob/main/src/handlers/pr-conventional-commits.js)
- [pr-signed-commits](https://github.com/TomerFi/auto-me-bot/blob/main/src/handlers/pr-signed-commits.js)
- [pr-tasks-list](https://github.com/TomerFi/auto-me-bot/blob/main/src/handlers/pr-tasks-list.js)

This is the handlers' distribution line:
https://github.com/TomerFi/auto-me-bot/blob/2bbcda75d7a7e814414e8a415214ffb1a537353f/src/auto-me-bot.js#L43

The handlers, for example, `pr-conventional-commits`, can access the following configuration:
```yaml
pr:
  conventionalCommits:
    x:
      y: z
```
like so:
```config.pr.conventionalCommits.x.y```
and, of course, can access any other configuration that exists in the configuration file.

If we change the following line, passing only the relevant configuration:
```js
invocations.push(handlers[key]()(context, config.pr[key], startedAt));
```
this should mean that for the example above, the `pr-conventional-commits` will access its configuration like so:
```x.y```
and will not have access to it's parent configuration.

**Comment by dolby360** [comment]
OK this one I can take :)
