### ISSUE TITLE
Bug in identifying bots with the pr-signed-commits handler

### ISSUE THREAD

**Issue by TomerFi** [TomerFi/auto-me-bot#47]
### What happened?

Technically, this line identifies bots, but it comes with a design bug (or even more):

https://github.com/TomerFi/auto-me-bot/blob/261e4e7f5d69fb3845bb627259cfb0c31ecdb202/src/handlers/pr-signed-commits.js#L36

> For the record, bots get a pass from signing off on their commits.

The `isBot` verification is being performed per handler request, and not per commit in the request.

As it is currently designed, for PRs with mixed commits, i.e. commits sourced by bots and commits sourced by humans, the `isBot` is based on the last commit.

An example I came across, a new PR was opened by `dependabot`, the `pr-signed-commits` workflow passed but some other workflow of mine had failed on account of the change brought forward by `depenedabot`'s dependency update.
Once I resolved and pushed it to the PR, my other workflow was passing, but  `pr-signed-commits` workflow was now constantly failing because the last commit was from my user, and I'm not a verified bot, so the handler expected `dependeabot` to signed off on its commits as well.

That being said, even though the handler is not supposed to expect bots to sign off on their commits, `dependabot` does!
So although cases like the example I described above are in fact a bug and shouldn't happen, when it does happen, for some reason (allegedly another bug), the handler is not able to verify `dependabot`'s sign-off trailer.

### Please provide runtime information.

Irrelevant.

### Relevant log output

```shell
An example of a commit message by `depenendabot`, which the handler wasn't able to pick up on its sign-off trailer:

build(deps-dev): bump flake8 from 4.0.1 to 5.0.1
Bumps [flake8](https://github.com/pycqa/flake8) from 4.0.1 to 5.0.1.
- [Release notes](https://github.com/pycqa/flake8/releases)
- [Commits](PyCQA/flake8@4.0.1...5.0.1)

---
updated-dependencies:
- dependency-name: flake8
  dependency-type: direct:development
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>
```

### How can this issue be reproduced?

- Wait for a PR by `dependabot`
- Verify the `pr-signed-commits` handler passes
- Add a commit of your own
- Verify the `pr-signed-commits` handler fails

**Comment by TomerFi** [comment]
Adding to the bot identification process, looks like for some cases, for instance, [this PR](https://github.com/TomerFi/version-bumper/pull/79) by `all-contributors`, I assume `context.payload.sender.type` is not enough to determine if the user is a bot.

Maybe we can add also take into account the user name, i.e. ends with `[bot]`.

**Comment by dolby360** [comment]
I have a few questions.
1. I don't really understand how PRs made by a bot involve human commits and vice versa.
2. As I understand you want to check each commit individually? If it's a bot then do not check, and for humans do check. 
3. In the second part you said that  `context.payload.sender.type` is not enough and you gave [this example](https://github.com/TomerFi/version-bumper/pull/79)
I'm not sure where did you get the type from.

**Comment by TomerFi** [comment]
A real example I bump into every now and then:

Let's say `dependabot` opened a PR updating a major version for a dependency and breaks your build.
**(for the example-sake, let's assume `dependabot` doesn't sign-off on its commits)**

The `pr-signed-commits` handler will get the event's payload for the PR, it will fetch one commit, the one from `dependabot`, and based on the following statement, which will return true, it will "give this commit a pass" without actually verifying the message trailer, the workflow run will be marked successful (as it should, because we don't care if bots sign-off on their commits or not):

https://github.com/TomerFi/auto-me-bot/blob/261e4e7f5d69fb3845bb627259cfb0c31ecdb202/src/handlers/pr-signed-commits.js#L36

Now, in order to fix the break caused by the dependency bump, you will push a commit with a fix to the `dependabot`'s source branch for the PR.

And now, `pr-signed-commits` gets another run, only the new payload has two commits, yours and `dependabot`'s.
You're the one who pushed the last commit and triggered the run, and as you're obviously not a bot (I hope 😉 ), the above statement, will return false.
This will make the handler verify the trailer for both commits, and it will fail the workflow as `dependabot`'s commit, doesn't have a signed-off trailer.

To overcome this, we need to verify if the committer is a bot per commit object, and not per event payload.
That's the design bug I'm referring to, this is my bad.

You can see an example of an event [here](https://docs.github.com/en/rest/commits/commits#list-commits), note that each `commit` object in the returning list, has a `commiter`, I assume we can check the name or email on that, and verify if it contains `[bot]` to decide whether or not the current commit object was done by a bot or not.

---

Having said that, this should be an issue for other bots, but not for `dependabot`, because as seen in the above example commit message, `dependabot` does use the signed-off trailer, so unless `Signed-off-by: dependabot[bot] <support@github.com>` fails the regex match, or there's another bug in the way, then the aforementioned design bug should not affect `dependabot`'s commits.

So, technically, the above bug might have just helped us find another bug.

---

Adding to that, I've noticed some cases for other bots (not `dependabot`), as explained here https://github.com/TomerFi/auto-me-bot/issues/47#issuecomment-1201286616,
even though the PR had only one commit, the one from the bot, the handler still fails for bots that doesn't use the signed-off trailer.

I haven't had a chance to investigate this yet, but if I have to guess, I would think that the `context.payload.sender.type` property, is only set to `Bot` for GitHub's own bots, i.e. `dependabot`.
And for other bots, like the `all-contributors` bot, which is not owned by GitHub, this will have another value, which will make the handler verify the trailer, and as `all-contributors`, doesn't signs-off on its commits, then this fails the CI.

But... technically, this is a side-effect of the original issue.
once we verify `isBot` per commit object and not per event payload, then this should be resolved as well, as AFAIK, `all-contributors` contains `[bot]` in its login name.

**Comment by TomerFi** [comment]
Here's what I had in mind to get you started:
Perhaps changing this:
```javascript
    let isBot = context.payload.sender.type === 'Bot'
    await Promise.all(allCommits.map(commit =>
        verifyCommitTrailer(commit.commit, isBot).catch(() => unsignedCommits.push(commit))))
```
to something like this (but nicer):
```javascript
    await Promise.all(allCommits.map(commit =>
        verifyCommitTrailer(commit.commit, commit.commit.commiter.email.includes('bot'))
            .catch(() => unsignedCommits.push(commit))))
```

---

A nicer way to do this would perhaps be to update the `verifyCommitTrailer` function,
as it already has the commit object it doesn't need to boolean object stating if it's a bot or not.

So this might be better replacing this:
```javascript
    let isBot = context.payload.sender.type === 'Bot'
    await Promise.all(allCommits.map(commit =>
        verifyCommitTrailer(commit.commit, isBot).catch(() => unsignedCommits.push(commit))))
```
with this:
```javascript
await Promise.all(allCommits.map(commit => verifyCommitTrailer(commit.commit)
        .catch(() => unsignedCommits.push(commit))))
```
and this:
```javascript
async function verifyCommitTrailer(commit, isBot) {
    // list all 'Signed-off-by' trailers matching the author or committer
    var trailerMatches = []
    commit.message.split(EOL).forEach(line => {
        let match = line.match(SIGN_OFF_TRAILER_REGEX);
        if (match !== null) {
            let signed = { name: match[1], email: `${match[2]}@${match[3]}` };
            if (
                isBot // bots get a pass as they are the signers but not the author or the committer
                || (signed.name === commit.author.name && signed.email === commit.author.email) // signed by author
                || (signed.name === commit.committer.name && signed.email === commit.committer.email) // signed by committer
            ) {
                trailerMatches.push(signed);
            }
        }
    });
```
with this:
```javascript
async function verifyCommitTrailer(commit) {
    // list all 'Signed-off-by' trailers matching the author or committer
    var trailerMatches = []
    commit.message.split(EOL).forEach(line => {
        let match = line.match(SIGN_OFF_TRAILER_REGEX);
        if (match !== null) {
            let signed = { name: match[1], email: `${match[2]}@${match[3]}` };
            if (
                commit.committer.email.includes('[bot]')
                || (signed.name === commit.author.name && signed.email === commit.author.email) // signed by author
                || (signed.name === commit.committer.name && signed.email === commit.committer.email) // signed by committer
            ) {
                trailerMatches.push(signed);
            }
        }
    });
```

**Comment by TomerFi** [comment]
I haven't tested the above - just brainstorming.
If you have a better idea - please do whatever you think is best.

**Comment by dolby360** [comment]
@TomerFi Thanks again for the detailed answer, I think it's all clear now. I can take this issue. I'm not sure if searching 'bot' string is the best solution (what about poor Abbott) [Bot] is better but how we can be sure all bots have this suffix?!
I suggest adding emailes_to_ignore to the configuration what do you think?

**Comment by TomerFi** [comment]
> I can take this issue

Thank you very much, this will be very much appreciated!

---

> I'm not sure if searching 'bot' string is the best solution

I'm with you on that, in fact, when I started this project,
I investigated other apps, and I noticed that other apps use this technique ([bot] string search).

Much like you, I didn't like it, so I went with `context.payload.sender.type`, in hindsight, that's the cause for this issue.
Anyway, if you can find another way to identify bots, I'm on board.

---

> how we can be sure all bots have this suffix?!

For the bots I work with, dependabot, all-contributors, trafico, pull-request-size, welcome, auto-approval, codecov, and I think a couple of others, I noticed that suffix.
Take a look [here](https://github.com/TomerFi/version-bumper/pull/79), note the `bot` mark next to the comments by the various bots.

That being said, technically, we only care about bots that push commits, bots that do other stuff, like labeling, merging, approving, modifying checks, modifying pr contents, etc, and this project too actually, are irrelevant to the `pr-signed-commits` handler.

And I did see the same being done by other apps, so I guess that this is quite common.
Nevertheless, I would prefer other techniques if you can find one, maybe we can investigate the [event](https://docs.github.com/en/rest/commits/commits#list-commits) a bit more, perhaps the `commiter` or `author` objects, has some reference for the user's type.

---

> suggest adding emailes_to_ignore.

That's a great idea for a new feature.
Sound cool, but it should be in an issue of its own.
😃

**Comment by TomerFi** [comment]
Opened https://github.com/TomerFi/auto-me-bot/issues/58 for the feature you suggested, thank you!
