### ISSUE TITLE
Use faker js for fake names and emails

### ISSUE THREAD

**Issue by dolby360** [TomerFi/auto-me-bot#60]
### What did you have in mind?

I think that using [faker.js](https://github.com/faker-js/faker) to generate names and emails is more standard in testing (I'm not really sure I got this by reading over the internet).

For example, this piece of test can use that.
```js
    const fakeAuthorName = 'Elias Author';
    const fakeAuthorEmail = 'elias.author@fake.mail';
    const fakeCommitterName = 'Ezekiel Committer';
    const fakeCommitterEmail = 'ezekiel.committer@fake.mail';
```

**Comment by TomerFi** [comment]
cool!
I didn't think `faker-js` is still around after the [endgame commit](https://www.google.com/search?q=faker.js+endgame).
